"""Historical events database (1068–2026) for LLM simulation reference.

Each entry: year, event (Chinese), scope ("china"/"world"), impact (one sentence).

Density:
  1068–1300: dense  (game's core period)
  1301–1700: medium
  1701–2026: sparse
Total: ~300 entries
"""

HISTORICAL_EVENTS = [
    # ===================== 1068–1100 北宋熙宁·元丰·元祐 =====================
    {"year": 1068, "event": "宋神宗即位，起用王安石推行变法", "scope": "china", "impact": "开启熙宁变法，深刻影响宋朝政治经济军事格局"},
    {"year": 1069, "event": "王安石设制置三司条例司，颁青苗法、均输法", "scope": "china", "impact": "新法触及大地主大商人利益，朝堂新旧党争由此始"},
    {"year": 1070, "event": "颁保甲法、农田水利法", "scope": "china", "impact": "保甲寓兵于农，水利大兴，然扰民亦甚"},
    {"year": 1071, "event": "塞尔柱大败拜占庭于曼齐刻尔特", "scope": "world", "impact": "拜占庭丧失小亚细亚腹地，触发十字军东征的远因"},
    {"year": 1071, "event": "宋军五路伐夏，先胜后败", "scope": "china", "impact": "对夏战略受挫，暴露宋军指挥与后勤弱点"},
    {"year": 1072, "event": "颁方田均税法、市易法", "scope": "china", "impact": "清丈田亩抑制兼并，政府直接参与商业，与商贾争利"},
    {"year": 1073, "event": "王韶收复熙河五州", "scope": "china", "impact": "北宋经略河湟最大胜利，断西夏右臂，拓疆二千余里"},
    {"year": 1075, "event": "宋越熙宁战争爆发", "scope": "china", "impact": "李朝入侵邕钦，宋反击入越，战后维持宗藩关系"},
    {"year": 1076, "event": "王安石罢相，新法由吕惠卿等推行", "scope": "china", "impact": "变法失去核心推动者，新党内部分裂"},
    {"year": 1077, "event": "宋辽划界争议，宋让地七百里", "scope": "china", "impact": "对辽退让示弱，反映宋廷避战求和心态"},
    {"year": 1079, "event": "苏轼因乌台诗案下狱", "scope": "china", "impact": "新旧党争走向人身迫害，文人士大夫寒心"},
    {"year": 1080, "event": "改元元丰，神宗亲政推行官制改革", "scope": "china", "impact": "整顿冗官，加强中央集权，新法进入深化期"},
    {"year": 1082, "event": "宋军永乐城之败，丧师二十万", "scope": "china", "impact": "对夏战略惨败，神宗精神受创，锐气大挫"},
    {"year": 1085, "event": "宋神宗崩，哲宗即位，高太后垂帘听政", "scope": "china", "impact": "旧党司马光执政，尽废新法（元祐更化）"},
    {"year": 1086, "event": "王安石卒；司马光卒", "scope": "china", "impact": "新法旧法两派灵魂人物同年凋零，党争却愈演愈烈"},
    {"year": 1088, "event": "世界最古老大学博洛尼亚大学创立", "scope": "world", "impact": "欧洲大学传统之始，推动中世纪学术复兴"},
    {"year": 1093, "event": "高太后崩，哲宗亲政，复行新法", "scope": "china", "impact": "新党章惇执政，报复旧党，党争升级为流放迫害"},
    {"year": 1096, "event": "教皇乌尔班二世号召第一次十字军东征", "scope": "world", "impact": "开启两百年十字军运动，深刻改变欧洲与中东格局"},
    {"year": 1099, "event": "十字军攻占耶路撒冷，建耶路撒冷王国", "scope": "world", "impact": "西方基督教势力首次在黎凡特建立持久据点"},
    # ===================== 1100–1127 北宋末年·靖康 =====================
    {"year": 1100, "event": "宋哲宗崩，徽宗即位", "scope": "china", "impact": "徽宗好大喜功、任用蔡京，北宋由盛转衰"},
    {"year": 1102, "event": "蔡京立元祐党籍碑，禁锢旧党", "scope": "china", "impact": "党争工具化，朝政日趋腐败"},
    {"year": 1105, "event": "宋设苏杭应奉局，大搜花石纲", "scope": "china", "impact": "竭民力以奉一人，东南怨声载道"},
    {"year": 1115, "event": "女真完颜阿骨打称帝建金", "scope": "china", "impact": "东北新兴强权崛起，将颠覆辽宋格局"},
    {"year": 1119, "event": "宋江起义于梁山泊", "scope": "china", "impact": "反映北宋末年民不聊生，虽被招安，社会矛盾尖锐"},
    {"year": 1120, "event": "方腊起义于睦州", "scope": "china", "impact": "花石纲之弊引发大规模民变，动摇东南根基"},
    {"year": 1120, "event": "宋金海上之盟，约夹攻辽", "scope": "china", "impact": "联金灭辽战略短视，自毁百年和约屏障"},
    {"year": 1122, "event": "宋军攻辽燕京惨败，金人遂轻宋", "scope": "china", "impact": "军力虚弱暴露无遗，金人萌生南侵之意"},
    {"year": 1125, "event": "金灭辽", "scope": "china", "impact": "契丹两百年帝国覆灭，金取代辽成为北方新霸主"},
    {"year": 1125, "event": "金兵第一次南下，徽宗禅位钦宗", "scope": "china", "impact": "北宋朝廷慌乱无措，太上皇与皇帝并立，决策混乱"},
    {"year": 1127, "event": "靖康之变，金兵破开封，掳徽钦二帝", "scope": "china", "impact": "北宋灭亡，中原沦陷，中国政治中心南移"},
    # ===================== 1127–1279 南宋 =====================
    {"year": 1127, "event": "赵构即位于应天府，南宋建立", "scope": "china", "impact": "宋室南渡，偏安江南，南北对峙格局延续百五十年"},
    {"year": 1129, "event": "金兵追击宋高宗入海，苗刘兵变", "scope": "china", "impact": "南宋政权风雨飘摇，武将专权初现"},
    {"year": 1130, "event": "金立刘豫伪齐政权", "scope": "china", "impact": "金以汉人治中原缓冲，宋金间增加战略纵深"},
    {"year": 1132, "event": "韩世忠黄天荡之战阻金兵", "scope": "china", "impact": "宋军水战优势初显，鼓舞抗战士气"},
    {"year": 1134, "event": "岳飞第一次北伐收复襄汉六郡", "scope": "china", "impact": "岳家军声威日隆，成为南宋北伐主力"},
    {"year": 1138, "event": "宋金第一次和议，秦桧主和", "scope": "china", "impact": "主和派得势，岳飞等主战派受压制"},
    {"year": 1140, "event": "岳飞郾城大捷，连战连捷", "scope": "china", "impact": "北伐最接近成功之时，却因十二道金牌功亏一篑"},
    {"year": 1141, "event": "绍兴和议，岳飞被害于风波亭", "scope": "china", "impact": "宋金划淮为界，南宋偏安定局，忠良蒙冤千古"},
    {"year": 1142, "event": "宋金绍兴和议正式成立", "scope": "china", "impact": "宋称臣纳贡，换取二十年和平，南北对峙格局确定"},
    {"year": 1147, "event": "第二次十字军东征失败", "scope": "world", "impact": "十字军运动受挫，穆斯林势力重新集结"},
    {"year": 1153, "event": "金迁都燕京（中都）", "scope": "china", "impact": "金朝全面汉化，政治中心南移，对南宋压力增大"},
    {"year": 1161, "event": "金海陵王南侵，虞允文采石之战大败金军", "scope": "china", "impact": "金内乱海陵王被弑，南宋转危为安"},
    {"year": 1162, "event": "宋孝宗即位，锐意恢复", "scope": "china", "impact": "南宋最有作为的皇帝，发动隆兴北伐"},
    {"year": 1163, "event": "隆兴北伐符离之败", "scope": "china", "impact": "北伐再败，孝宗锐气受挫，转向内治"},
    {"year": 1165, "event": "宋金隆兴和议，改君臣为叔侄", "scope": "china", "impact": "南宋地位略有提升，和平维持四十年"},
    {"year": 1171, "event": "萨拉丁推翻法蒂玛王朝，建阿尤布王朝", "scope": "world", "impact": "埃及重归逊尼派，穆斯林统一力量对抗十字军"},
    {"year": 1187, "event": "萨拉丁收复耶路撒冷", "scope": "world", "impact": "十字军丧失圣城，触发第三次十字军东征"},
    {"year": 1189, "event": "第三次十字军东征开始", "scope": "world", "impact": "狮心王理查与萨拉丁对决，东西方文明碰撞"},
    {"year": 1192, "event": "源赖朝建立镰仓幕府", "scope": "world", "impact": "日本进入武家政治时代，天皇权力虚化"},
    {"year": 1194, "event": "宋宁宗即位，韩侂胄专权", "scope": "china", "impact": "外戚干政，政治日趋腐败"},
    {"year": 1202, "event": "第四次十字军攻陷君士坦丁堡", "scope": "world", "impact": "拜占庭帝国遭受重创，东西方基督教世界分裂加剧"},
    {"year": 1206, "event": "铁木真统一蒙古，尊号成吉思汗", "scope": "world", "impact": "蒙古帝国崛起，将改变整个欧亚大陆格局"},
    {"year": 1206, "event": "韩侂胄开禧北伐失败", "scope": "china", "impact": "北伐仓促再败，韩侂胄被杀函首送金"},
    {"year": 1208, "event": "宋金嘉定和议，改叔侄为伯侄", "scope": "china", "impact": "南宋地位再降，岁币增加，屈辱愈甚"},
    {"year": 1211, "event": "蒙古伐金，野狐岭之战大败金军", "scope": "china", "impact": "金朝主力覆灭，北方格局根本逆转"},
    {"year": 1215, "event": "蒙古攻陷金中都（北京）", "scope": "china", "impact": "金朝丧失北方根本，被迫南迁开封"},
    {"year": 1215, "event": "英格兰颁布大宪章", "scope": "world", "impact": "限制王权之始，现代宪政与法治的远源"},
    {"year": 1218, "event": "蒙古第一次西征，灭花剌子模", "scope": "world", "impact": "蒙古铁骑踏入中亚西亚，丝绸之路沿线诸国覆灭"},
    {"year": 1223, "event": "蒙古击败罗斯诸公国", "scope": "world", "impact": "罗斯进入蒙古统治时代，东欧历史进程改写"},
    {"year": 1227, "event": "成吉思汗崩，窝阔台继位", "scope": "world", "impact": "蒙古扩张暂歇后更猛烈推进"},
    {"year": 1227, "event": "蒙古灭西夏", "scope": "china", "impact": "党项两百年国家灭亡，河西走廊归入蒙古"},
    {"year": 1231, "event": "蒙古高丽战争，高丽成为藩属", "scope": "china", "impact": "蒙古势力延伸至朝鲜半岛"},
    {"year": 1234, "event": "蒙古与宋联军灭金", "scope": "china", "impact": "金朝灭亡，宋蒙直接接壤，新的大患来临"},
    {"year": 1235, "event": "蒙古建和林为都，第二次西征开始", "scope": "world", "impact": "蒙古铁骑横扫东欧，欧洲陷入恐慌"},
    {"year": 1235, "event": "蒙古首次攻宋，宋蒙战争爆发", "scope": "china", "impact": "南宋面临前所未有的强大敌人"},
    {"year": 1241, "event": "蒙古兵临维也纳城下，窝阔台崩退兵", "scope": "world", "impact": "欧洲免于蒙古铁蹄，但东欧已遭蹂躏"},
    {"year": 1247, "event": "凉州会盟，吐蕃归附蒙古", "scope": "china", "impact": "西藏纳入中国版图的历史起点"},
    {"year": 1253, "event": "蒙古灭大理", "scope": "china", "impact": "南宋西南方失去屏障，蒙古完成对宋的战略包围"},
    {"year": 1258, "event": "蒙古旭烈兀攻陷巴格达，灭阿拔斯王朝", "scope": "world", "impact": "伊斯兰世界中心覆灭，中东格局彻底改变"},
    {"year": 1258, "event": "蒙哥汗亲征南宋，钓鱼城之战蒙哥崩", "scope": "china", "impact": "蒙古大汗阵亡，西征中断，忽必烈与阿里不哥争位"},
    {"year": 1260, "event": "忽必烈即大汗位，建元中统", "scope": "china", "impact": "蒙古帝国走向汉化与分裂，元朝雏形显现"},
    {"year": 1265, "event": "英国首次召开国会", "scope": "world", "impact": "代议制政体的早期实践"},
    # ===================== 1271–1300 元朝统一 =====================
    {"year": 1271, "event": "忽必烈定国号为大元", "scope": "china", "impact": "蒙古政权正式成为中国王朝，取《易经》'大哉乾元'"},
    {"year": 1274, "event": "元军第一次远征日本，遇台风败归", "scope": "world", "impact": "神风传说起源，日本免于蒙古征服"},
    {"year": 1276, "event": "元军攻陷临安，南宋朝廷降", "scope": "china", "impact": "南宋实质灭亡，三百年赵宋政权终结"},
    {"year": 1279, "event": "崖山海战，南宋残部覆灭", "scope": "china", "impact": "古典中国第一次全面亡于游牧民族，士大夫殉国无数"},
    {"year": 1281, "event": "元军第二次远征日本再遭台风", "scope": "world", "impact": "日本再免蒙古征服，神风信仰深植日本文化"},
    {"year": 1283, "event": "文天祥就义", "scope": "china", "impact": "民族气节象征，'人生自古谁无死'千古流传"},
    {"year": 1285, "event": "元征安南（越南）失败", "scope": "china", "impact": "蒙古骑兵不适应热带丛林作战"},
    {"year": 1287, "event": "元征缅甸，蒲甘王朝衰亡", "scope": "world", "impact": "东南亚政治版图因蒙古入侵而重组"},
    {"year": 1291, "event": "马可波罗离开中国", "scope": "world", "impact": "其游记将激发欧洲对东方的向往，推动大航海时代"},
    {"year": 1294, "event": "忽必烈崩", "scope": "china", "impact": "元朝由盛转衰，继位纷争不断"},
    {"year": 1295, "event": "英格兰召开模范国会", "scope": "world", "impact": "英国议会制度进一步发展"},
    {"year": 1299, "event": "奥斯曼帝国建立", "scope": "world", "impact": "日后将灭亡拜占庭、称霸中东欧的小帝国起步"},
    # ===================== 1301–1400 元末明初 =====================
    {"year": 1303, "event": "元朝朱清、张瑄海运漕粮至大都", "scope": "china", "impact": "南北经济命脉改由海路维系"},
    {"year": 1313, "event": "元恢复科举，蒙古色目人与汉人分榜", "scope": "china", "impact": "民族歧视制度化，社会矛盾加深"},
    {"year": 1323, "event": "南坡之变，元英宗被弑", "scope": "china", "impact": "元朝皇位争夺白热化，政治持续动荡"},
    {"year": 1336, "event": "元顺帝罢科举", "scope": "china", "impact": "汉族士人上升通道断绝，离心力加剧"},
    {"year": 1337, "event": "英法百年战争爆发", "scope": "world", "impact": "英法两国百年对抗重塑欧洲民族国家格局"},
    {"year": 1346, "event": "黑死病从克里米亚传入欧洲", "scope": "world", "impact": "鼠疫将夺去欧洲三分之一人口，彻底改变社会结构"},
    {"year": 1348, "event": "黑死病肆虐欧洲高峰", "scope": "world", "impact": "劳动力锐减动摇封建制，催生文艺复兴的社会条件"},
    {"year": 1351, "event": "红巾军起义爆发", "scope": "china", "impact": "元末农民大起义席卷全国，元朝统治土崩瓦解"},
    {"year": 1356, "event": "朱元璋攻克集庆（南京），以此为基", "scope": "china", "impact": "朱元璋建立根据地，逐步统一南方"},
    {"year": 1356, "event": "普瓦捷战役英军大胜，法王被俘", "scope": "world", "impact": "百年战争英方占优，法国危机深重"},
    {"year": 1358, "event": "法国扎克雷农民起义", "scope": "world", "impact": "黑死病后社会矛盾爆发，封建秩序动摇"},
    {"year": 1368, "event": "朱元璋称帝建明，元顺帝北逃", "scope": "china", "impact": "蒙古在中原近百年统治终结，汉族政权恢复"},
    {"year": 1371, "event": "明朝废行省设三司", "scope": "china", "impact": "中央集权加强，地方权力分割制衡"},
    {"year": 1380, "event": "胡惟庸案，废丞相制度", "scope": "china", "impact": "延续千年的丞相制度终结，皇权空前强化"},
    {"year": 1381, "event": "明朝编赋役黄册、推行里甲制", "scope": "china", "impact": "基层治理体系确立，户籍赋役管理严密化"},
    {"year": 1389, "event": "科索沃战役，塞尔维亚败于奥斯曼", "scope": "world", "impact": "巴尔干半岛逐步落入奥斯曼势力范围"},
    # ===================== 1401–1500 明朝前期 =====================
    {"year": 1398, "event": "明太祖崩，建文帝即位", "scope": "china", "impact": "削藩引发靖难之役的前奏"},
    {"year": 1402, "event": "朱棣靖难之役成功，即位为明成祖", "scope": "china", "impact": "皇位更替，明朝政策走向全面转向扩张"},
    {"year": 1405, "event": "郑和第一次下西洋", "scope": "china", "impact": "人类航海史壮举，中国海上力量达到巅峰"},
    {"year": 1415, "event": "阿金库尔战役，英军以少胜多", "scope": "world", "impact": "百年战争英方再占上风"},
    {"year": 1420, "event": "明成祖迁都北京", "scope": "china", "impact": "天子守国门，政治中心北移，影响深远"},
    {"year": 1421, "event": "郑和第六次下西洋到达非洲东海岸", "scope": "china", "impact": "中国航海最远到达非洲，此后再无远航"},
    {"year": 1429, "event": "圣女贞德解奥尔良之围", "scope": "world", "impact": "法国百年战争转机，民族意识觉醒"},
    {"year": 1433, "event": "郑和第七次下西洋，此后明朝海禁", "scope": "china", "impact": "中国主动退出大航海竞争，海洋霸权拱手让与西方"},
    {"year": 1438, "event": "古腾堡发明活字印刷术", "scope": "world", "impact": "信息传播革命，推动文艺复兴与宗教改革"},
    {"year": 1449, "event": "土木堡之变，明英宗被瓦剌俘获", "scope": "china", "impact": "明朝由盛转衰的转折点，北方边患加剧"},
    {"year": 1453, "event": "奥斯曼攻陷君士坦丁堡，拜占庭灭亡", "scope": "world", "impact": "千年东罗马帝国终结，中世纪结束的标志"},
    {"year": 1453, "event": "百年战争结束，法国获胜", "scope": "world", "impact": "英法民族国家成型，欧洲格局重塑"},
    {"year": 1455, "event": "玫瑰战争爆发", "scope": "world", "impact": "英格兰内战三十年，都铎王朝由此诞生"},
    {"year": 1467, "event": "日本应仁之乱，战国时代开始", "scope": "world", "impact": "日本进入百年战乱，武家社会彻底洗牌"},
    {"year": 1479, "event": "西班牙完成收复失地运动", "scope": "world", "impact": "伊比利亚半岛基督徒驱逐穆斯林，西班牙统一"},
    {"year": 1487, "event": "葡萄牙迪亚士到达好望角", "scope": "world", "impact": "欧洲航海首次绕过非洲南端，通往印度在望"},
    {"year": 1488, "event": "明朝弘治中兴", "scope": "china", "impact": "明孝宗励精图治，政治清明，难得的治世"},
    {"year": 1492, "event": "哥伦布到达美洲", "scope": "world", "impact": "大航海时代最关键事件，新旧大陆碰撞改变世界"},
    {"year": 1494, "event": "西班牙葡萄牙签署托德西利亚斯条约", "scope": "world", "impact": "教皇仲裁瓜分世界，殖民秩序的起点"},
    {"year": 1498, "event": "达伽马到达印度", "scope": "world", "impact": "欧洲直通东方航路开辟，传统丝路贸易衰落"},
    # ===================== 1501–1600 明朝中期·大航海 =====================
    {"year": 1500, "event": "葡萄牙卡布拉尔到达巴西", "scope": "world", "impact": "南美最大国家此后三百年为葡萄牙殖民地"},
    {"year": 1509, "event": "葡萄牙在第乌海战击败穆斯林舰队", "scope": "world", "impact": "欧洲海上力量首次在印度洋确立优势"},
    {"year": 1510, "event": "葡萄牙占领果阿", "scope": "world", "impact": "欧洲在亚洲建立首个殖民据点"},
    {"year": 1511, "event": "葡萄牙攻占马六甲", "scope": "world", "impact": "东西方贸易枢纽易手，伊斯兰海上贸易网络受创"},
    {"year": 1513, "event": "葡萄牙人首次到达中国海岸", "scope": "china", "impact": "大航海时代西方势力叩响中国大门"},
    {"year": 1517, "event": "马丁·路德发表九十五条论纲", "scope": "world", "impact": "宗教改革运动爆发，基督教世界分裂，现代思想自由萌芽"},
    {"year": 1519, "event": "麦哲伦开始环球航行", "scope": "world", "impact": "人类首次环球航行，证明地球是圆的"},
    {"year": 1521, "event": "明武宗崩，世宗即位；大礼议之争", "scope": "china", "impact": "嘉靖初年政治激荡，皇权与礼制之争"},
    {"year": 1521, "event": "阿兹特克帝国被西班牙征服", "scope": "world", "impact": "中美洲文明遭毁灭性打击，殖民掠夺开始"},
    {"year": 1522, "event": "麦哲伦船队完成环球航行", "scope": "world", "impact": "大航海时代里程碑，全球航路贯通"},
    {"year": 1526, "event": "莫卧儿帝国建立", "scope": "world", "impact": "印度次大陆进入新的统一王朝时期"},
    {"year": 1533, "event": "印加帝国被西班牙征服", "scope": "world", "impact": "南美文明遭毁灭，西班牙获得巨额白银"},
    {"year": 1534, "event": "英王亨利八世与罗马教廷决裂", "scope": "world", "impact": "英国国教建立，宗教改革与王权扩张并行"},
    {"year": 1543, "event": "哥白尼《天体运行论》出版", "scope": "world", "impact": "日心说挑战地心说，科学革命的起点"},
    {"year": 1543, "event": "葡萄牙人到达日本", "scope": "world", "impact": "火绳枪传入日本，深刻改变日本战国战争形态"},
    {"year": 1550, "event": "庚戌之变，俺答汗兵临北京城下", "scope": "china", "impact": "明朝边防危机暴露，被迫开马市议和"},
    {"year": 1553, "event": "葡萄牙人入居澳门", "scope": "china", "impact": "西方在华首个据点，东西方贸易窗口开启"},
    {"year": 1555, "event": "奥格斯堡和约，确立'教随国定'原则", "scope": "world", "impact": "宗教宽容迈出第一步，欧洲宗教战争暂息"},
    {"year": 1556, "event": "嘉靖大地震，死亡约83万人", "scope": "china", "impact": "人类有记载以来死亡人数最多的地震"},
    {"year": 1564, "event": "莎士比亚出生", "scope": "world", "impact": "英语文学最伟大的作家诞生"},
    {"year": 1565, "event": "西班牙在菲律宾建立殖民地", "scope": "world", "impact": "马尼拉大帆船贸易连接亚洲与美洲"},
    {"year": 1566, "event": "荷兰独立战争（八十年战争）爆发", "scope": "world", "impact": "荷兰将从西班牙统治中崛起为海上霸主"},
    {"year": 1571, "event": "勒班陀海战，神圣同盟击败奥斯曼海军", "scope": "world", "impact": "奥斯曼海上扩张受挫，地中海力量平衡转变"},
    {"year": 1572, "event": "圣巴托洛缪大屠杀", "scope": "world", "impact": "法国宗教战争最惨烈一幕，数万胡格诺派被杀"},
    {"year": 1578, "event": "张居正推行一条鞭法", "scope": "china", "impact": "赋役制度改革，简化税制，增加财政收入"},
    {"year": 1582, "event": "张居正卒，改革人亡政息", "scope": "china", "impact": "明朝最后一次振兴机会丧失，此后每况愈下"},
    {"year": 1582, "event": "利玛窦来华", "scope": "china", "impact": "西学东渐之始，中西文化交流新篇章"},
    {"year": 1588, "event": "英国击败西班牙无敌舰队", "scope": "world", "impact": "海上霸权从西班牙向英国转移的标志性事件"},
    {"year": 1592, "event": "日本丰臣秀吉入侵朝鲜，壬辰倭乱", "scope": "china", "impact": "明朝出兵援朝，七年战争消耗国力"},
    {"year": 1598, "event": "壬辰倭乱结束，日本退兵", "scope": "china", "impact": "东亚三国均元气大伤，日本进入德川锁国"},
    # ===================== 1601–1700 明末清初·科学革命 =====================
    {"year": 1600, "event": "布鲁诺被宗教裁判所烧死", "scope": "world", "impact": "思想自由与宗教权威的冲突达到极端"},
    {"year": 1600, "event": "英国东印度公司成立", "scope": "world", "impact": "殖民扩张的制度化工具，将深刻改变亚洲"},
    {"year": 1602, "event": "荷兰东印度公司成立", "scope": "world", "impact": "世界第一家股份制公司，资本主义制度创新"},
    {"year": 1605, "event": "塞万提斯《堂吉诃德》出版", "scope": "world", "impact": "现代小说的起点，欧洲文学里程碑"},
    {"year": 1609, "event": "伽利略用望远镜观测天体", "scope": "world", "impact": "实证科学方法的确立，科学革命加速"},
    {"year": 1610, "event": "明朝国本之争结束，光宗即位一月而崩", "scope": "china", "impact": "明末宫廷政治混乱，党争白热化"},
    {"year": 1616, "event": "努尔哈赤建立后金", "scope": "china", "impact": "满洲崛起，明朝东北边患日益严峻"},
    {"year": 1618, "event": "三十年战争爆发", "scope": "world", "impact": "欧洲最惨烈的宗教战争，将重塑德意志格局"},
    {"year": 1619, "event": "萨尔浒之战，明军大败于后金", "scope": "china", "impact": "明在辽东的战略主动权彻底丧失"},
    {"year": 1620, "event": "五月花号到达北美", "scope": "world", "impact": "英国清教徒建立北美殖民地，美国文明的起点"},
    {"year": 1624, "event": "魏忠贤阉党专权", "scope": "china", "impact": "明末政治最黑暗时期，东林党人惨遭迫害"},
    {"year": 1628, "event": "崇祯帝即位，除魏忠贤", "scope": "china", "impact": "明末最后的努力，但积重难返"},
    {"year": 1628, "event": "陕西大旱，农民起义蜂起", "scope": "china", "impact": "明末农民大起义开端，李自成张献忠起兵"},
    {"year": 1632, "event": "伽利略《关于两大世界体系的对话》出版", "scope": "world", "impact": "日心说的系统辩护，科学革命核心文献"},
    {"year": 1636, "event": "皇太极改国号为清", "scope": "china", "impact": "后金正式称清，取代明朝天命的意图昭然"},
    {"year": 1637, "event": "日本岛原之乱后锁国", "scope": "world", "impact": "日本闭关锁国两百年，退出世界舞台"},
    {"year": 1637, "event": "笛卡尔《方法论》出版", "scope": "world", "impact": "理性主义哲学奠基，现代思维方法的起点"},
    {"year": 1640, "event": "英国长期国会召开，英国内战前奏", "scope": "world", "impact": "国王与议会矛盾激化，革命风暴将至"},
    {"year": 1642, "event": "英国内战爆发", "scope": "world", "impact": "国王被送上断头台，共和制首次在大国实践"},
    {"year": 1644, "event": "李自成入京，崇祯帝自缢，明亡", "scope": "china", "impact": "明朝灭亡，中国再次陷入政权更替的混乱"},
    {"year": 1644, "event": "清军入关，定都北京", "scope": "china", "impact": "满族入主中原，开始近三百年清朝统治"},
    {"year": 1645, "event": "清颁布剃发令，嘉定三屠", "scope": "china", "impact": "民族压迫政策引发激烈抵抗，江南惨遭屠戮"},
    {"year": 1648, "event": "威斯特伐利亚和约签订", "scope": "world", "impact": "三十年战争结束，现代国际关系体系与民族国家原则确立"},
    {"year": 1649, "event": "英王查理一世被处死", "scope": "world", "impact": "欧洲君主首次被革命法庭处决，震撼整个欧洲"},
    {"year": 1652, "event": "第一次英荷战争", "scope": "world", "impact": "海上霸权争夺战，英国开始挑战荷兰"},
    {"year": 1659, "event": "郑成功起兵反清", "scope": "china", "impact": "南明最后的抗清力量坚持东南沿海"},
    {"year": 1661, "event": "郑成功收复台湾", "scope": "china", "impact": "驱逐荷兰殖民者，中国收回台湾"},
    {"year": 1661, "event": "康熙帝即位", "scope": "china", "impact": "中国在位最长的皇帝，开创康乾盛世"},
    {"year": 1662, "event": "永历帝被杀，南明覆灭", "scope": "china", "impact": "明朝残余势力彻底覆灭"},
    {"year": 1665, "event": "牛顿发现万有引力定律", "scope": "world", "impact": "科学革命最伟大的发现，经典物理学奠基"},
    {"year": 1667, "event": "康熙擒鳌拜，亲政开始", "scope": "china", "impact": "少年皇帝展现雄才，开启自主执政"},
    {"year": 1673, "event": "三藩之乱爆发", "scope": "china", "impact": "清朝最大的内乱，历时八年方平"},
    {"year": 1683, "event": "清军攻克台湾，统一中国", "scope": "china", "impact": "台湾纳入清朝版图，中国重新统一"},
    {"year": 1683, "event": "奥斯曼围攻维也纳失败", "scope": "world", "impact": "奥斯曼扩张由盛转衰的转折点"},
    {"year": 1687, "event": "牛顿《自然哲学的数学原理》出版", "scope": "world", "impact": "科学革命集大成之作，现代物理学诞生"},
    {"year": 1688, "event": "英国光荣革命", "scope": "world", "impact": "不流血的革命确立君主立宪，现代民主制度的重要一步"},
    {"year": 1689, "event": "中俄尼布楚条约签订", "scope": "china", "impact": "中国首次与西方列强签订平等条约，确定东段边界"},
    {"year": 1689, "event": "英国权利法案通过", "scope": "world", "impact": "君主立宪制法律化，议会主权确立"},
    # ===================== 1701–1800 清朝鼎盛·启蒙运动 =====================
    {"year": 1701, "event": "西班牙王位继承战争爆发", "scope": "world", "impact": "欧洲权力再平衡，英国崛起为一流强国"},
    {"year": 1707, "event": "英格兰与苏格兰合并为大不列颠王国", "scope": "world", "impact": "英伦三岛统一，大英帝国基础奠定"},
    {"year": 1713, "event": "乌得勒支和约，英国获直布罗陀", "scope": "world", "impact": "英国地中海战略据点确立至今"},
    {"year": 1721, "event": "俄罗斯帝国成立，彼得大帝称帝", "scope": "world", "impact": "俄国正式跻身欧洲大国行列"},
    {"year": 1722, "event": "康熙帝崩，雍正即位", "scope": "china", "impact": "雍正厉行改革，整顿吏治与财政"},
    {"year": 1723, "event": "雍正推行摊丁入亩", "scope": "china", "impact": "人头税并入田赋，减轻贫民负担，人口增长加速"},
    {"year": 1735, "event": "雍正帝崩，乾隆即位", "scope": "china", "impact": "清朝进入全盛时期，也是盛极而衰的开始"},
    {"year": 1740, "event": "奥地利王位继承战争", "scope": "world", "impact": "普鲁士崛起，德意志二元格局形成"},
    {"year": 1748, "event": "孟德斯鸠《论法的精神》出版", "scope": "world", "impact": "三权分立理论奠基，深刻影响现代宪政设计"},
    {"year": 1751, "event": "狄德罗《百科全书》开始出版", "scope": "world", "impact": "启蒙运动的核心工程，系统传播理性与科学"},
    {"year": 1756, "event": "七年战争爆发", "scope": "world", "impact": "第一次全球性战争，英国获法国北美殖民地"},
    {"year": 1757, "event": "乾隆下令一口通商，广州十三行", "scope": "china", "impact": "闭关锁国政策制度化，中国与世界渐行渐远"},
    {"year": 1762, "event": "卢梭《社会契约论》出版", "scope": "world", "impact": "人民主权学说奠基，法国大革命的思想武器"},
    {"year": 1765, "event": "哈格里夫斯发明珍妮纺纱机", "scope": "world", "impact": "工业革命的序幕拉开，机器生产取代手工"},
    {"year": 1769, "event": "瓦特改良蒸汽机", "scope": "world", "impact": "工业革命的核心动力，人类进入蒸汽时代"},
    {"year": 1773, "event": "波士顿倾茶事件", "scope": "world", "impact": "美国独立运动的导火索"},
    {"year": 1776, "event": "美国独立宣言发表", "scope": "world", "impact": "第一个近代共和国诞生，启蒙思想的政治实践"},
    {"year": 1776, "event": "亚当·斯密《国富论》出版", "scope": "world", "impact": "现代经济学奠基，自由市场理论确立"},
    {"year": 1782, "event": "《四库全书》编纂完成", "scope": "china", "impact": "最大规模的文化工程，亦伴随大量书籍被禁毁"},
    {"year": 1783, "event": "美国独立战争胜利", "scope": "world", "impact": "大英帝国首次失去重要殖民地，共和制度立足"},
    {"year": 1789, "event": "法国大革命爆发，攻占巴士底狱", "scope": "world", "impact": "欧洲君主制的最大冲击，现代民主与民族主义浪潮的起点"},
    {"year": 1791, "event": "海地革命爆发", "scope": "world", "impact": "唯一成功的奴隶起义，建立首个黑人共和国"},
    {"year": 1793, "event": "路易十六被送上断头台", "scope": "world", "impact": "欧洲君主的恐惧达到顶点，反法同盟形成"},
    {"year": 1793, "event": "马嘎尔尼使团访华，乾隆拒绝通商", "scope": "china", "impact": "中国错失与工业文明接轨的最后机会"},
    {"year": 1796, "event": "白莲教起义爆发", "scope": "china", "impact": "清朝由盛转衰的标志，耗尽国库元气"},
    {"year": 1799, "event": "乾隆帝崩，嘉庆亲政，和珅被赐死", "scope": "china", "impact": "和珅跌倒嘉庆吃饱，但体制性腐败已无法根除"},
    # ===================== 1801–1900 晚清·工业革命 =====================
    {"year": 1804, "event": "拿破仑加冕称帝", "scope": "world", "impact": "共和国变帝国，但拿破仑法典传播革命理念"},
    {"year": 1804, "event": "世界首条蒸汽机车铁路出现", "scope": "world", "impact": "铁路时代开启，重塑交通与经济地理"},
    {"year": 1806, "event": "神圣罗马帝国解散", "scope": "world", "impact": "千年帝国终结，德意志民族主义兴起"},
    {"year": 1812, "event": "拿破仑远征俄国惨败", "scope": "world", "impact": "拿破仑帝国由盛转衰的转折点"},
    {"year": 1815, "event": "滑铁卢战役，拿破仑最终失败", "scope": "world", "impact": "维也纳体系确立，欧洲恢复君主制秩序"},
    {"year": 1820, "event": "嘉庆帝崩，道光即位", "scope": "china", "impact": "清朝进入衰落期，内忧外患加剧"},
    {"year": 1825, "event": "世界首条公共铁路在英国开通", "scope": "world", "impact": "铁路革命正式改变人类社会"},
    {"year": 1830, "event": "法国七月革命", "scope": "world", "impact": "波旁王朝再次被推翻，欧洲革命浪潮涌动"},
    {"year": 1837, "event": "维多利亚女王即位", "scope": "world", "impact": "大英帝国鼎盛时代开始，日不落帝国"},
    {"year": 1839, "event": "林则徐虎门销烟", "scope": "china", "impact": "中英鸦片战争导火索，中国近代史开端"},
    {"year": 1840, "event": "鸦片战争爆发", "scope": "china", "impact": "中国百年屈辱史的开端，被迫卷入近代世界体系"},
    {"year": 1842, "event": "南京条约签订，割让香港", "scope": "china", "impact": "中国第一个不平等条约，半殖民地化开始"},
    {"year": 1848, "event": "《共产党宣言》发表", "scope": "world", "impact": "马克思主义诞生，将深刻影响20世纪世界格局"},
    {"year": 1848, "event": "欧洲革命浪潮", "scope": "world", "impact": "多国君主制受冲击，民族主义与自由主义高涨"},
    {"year": 1851, "event": "太平天国起义爆发", "scope": "china", "impact": "中国历史上最大规模农民战争，人口损失数千万"},
    {"year": 1853, "event": "美国佩里舰队叩关日本", "scope": "world", "impact": "日本被迫开国，明治维新的远因"},
    {"year": 1853, "event": "克里米亚战争爆发", "scope": "world", "impact": "俄国扩张受挫，欧洲均势维护"},
    {"year": 1856, "event": "第二次鸦片战争爆发", "scope": "china", "impact": "中国进一步沦为半殖民地"},
    {"year": 1858, "event": "中俄瑷珲条约，割让外东北", "scope": "china", "impact": "中国丧失大片领土，沙俄东扩得逞"},
    {"year": 1860, "event": "英法联军火烧圆明园", "scope": "china", "impact": "中国文化瑰宝遭毁灭，民族耻辱深重"},
    {"year": 1861, "event": "美国南北战争爆发", "scope": "world", "impact": "奴隶制存废之战，美国统一的血火洗礼"},
    {"year": 1861, "event": "慈禧太后开始垂帘听政", "scope": "china", "impact": "中国近半个世纪的实际统治者登场"},
    {"year": 1864, "event": "太平天国覆灭", "scope": "china", "impact": "十四年战乱结束，江南经济遭受重创"},
    {"year": 1865, "event": "美国内战结束，奴隶制废除", "scope": "world", "impact": "美国统一维护，为崛起为世界强国铺路"},
    {"year": 1868, "event": "日本明治维新开始", "scope": "world", "impact": "日本从封建国家转型为现代工业国，东亚格局巨变"},
    {"year": 1869, "event": "苏伊士运河开通", "scope": "world", "impact": "东西方航程缩短，全球贸易格局重塑"},
    {"year": 1870, "event": "普法战争，拿破仑三世被俘", "scope": "world", "impact": "德意志统一完成，欧洲权力中心转移"},
    {"year": 1871, "event": "德意志帝国成立", "scope": "world", "impact": "欧洲新霸主崛起，打破原有均势"},
    {"year": 1871, "event": "巴黎公社", "scope": "world", "impact": "无产阶级政权的第一次短暂实践"},
    {"year": 1876, "event": "贝尔发明电话", "scope": "world", "impact": "通信革命开始"},
    {"year": 1879, "event": "爱迪生发明实用电灯", "scope": "world", "impact": "电气时代来临，人类照明与动力革命"},
    {"year": 1884, "event": "中法战争", "scope": "china", "impact": "法国夺取越南宗主权，清朝藩属体系瓦解"},
    {"year": 1894, "event": "甲午中日战争爆发", "scope": "china", "impact": "清朝惨败于日本，东亚传统秩序崩塌"},
    {"year": 1895, "event": "马关条约签订，割让台湾", "scope": "china", "impact": "中国半殖民地化加深，民族危机空前"},
    {"year": 1898, "event": "戊戌变法失败，百日维新终结", "scope": "china", "impact": "自上而下改良道路受挫，革命思潮兴起"},
    {"year": 1899, "event": "义和团运动兴起", "scope": "china", "impact": "反帝排外运动，将引发八国联军侵华"},
    # ===================== 1901–2026 二十世纪·现代 =====================
    {"year": 1900, "event": "八国联军侵华，攻占北京", "scope": "china", "impact": "清朝彻底沦为半殖民地，民族危机达于极点"},
    {"year": 1901, "event": "辛丑条约签订", "scope": "china", "impact": "巨额赔款加深民族苦难，清朝名存实亡"},
    {"year": 1905, "event": "日俄战争在中国东北爆发", "scope": "china", "impact": "两个帝国主义在中国领土上开战，中国主权尽失"},
    {"year": 1905, "event": "同盟会成立，孙中山提出三民主义", "scope": "china", "impact": "近代中国民主革命有了统一的组织与纲领"},
    {"year": 1908, "event": "福特T型车量产", "scope": "world", "impact": "汽车进入大众消费，工业流水线革命"},
    {"year": 1910, "event": "日本吞并朝鲜", "scope": "world", "impact": "朝鲜半岛进入三十五年殖民时期"},
    {"year": 1911, "event": "辛亥革命爆发，清朝灭亡", "scope": "china", "impact": "延续两千年的帝制终结，亚洲第一个共和国成立"},
    {"year": 1912, "event": "中华民国成立，孙中山就任临时大总统", "scope": "china", "impact": "共和政体在中国首次实践"},
    {"year": 1914, "event": "第一次世界大战爆发", "scope": "world", "impact": "人类首次全球性战争，旧帝国秩序崩塌"},
    {"year": 1917, "event": "俄国十月革命", "scope": "world", "impact": "世界上第一个社会主义国家诞生，改变20世纪格局"},
    {"year": 1918, "event": "第一次世界大战结束", "scope": "world", "impact": "德奥俄土四大帝国瓦解，国际秩序重组"},
    {"year": 1919, "event": "五四运动爆发", "scope": "china", "impact": "中国新民主主义革命的开端，民族觉醒"},
    {"year": 1921, "event": "中国共产党成立", "scope": "china", "impact": "深刻改变中国与世界的政治力量诞生"},
    {"year": 1922, "event": "苏联成立", "scope": "world", "impact": "社会主义从理论到实践的第一个大国"},
    {"year": 1929, "event": "世界经济大萧条开始", "scope": "world", "impact": "资本主义最深重的危机，法西斯主义崛起的温床"},
    {"year": 1931, "event": "九一八事变，日本侵占东北", "scope": "china", "impact": "日本侵华开端，中国局部抗战开始"},
    {"year": 1933, "event": "希特勒上台，纳粹德国建立", "scope": "world", "impact": "欧洲走向战争，人类最黑暗的一页即将翻开"},
    {"year": 1934, "event": "红军长征开始", "scope": "china", "impact": "中国共产党战略转移，革命火种得以保存"},
    {"year": 1937, "event": "七七事变，全面抗战爆发", "scope": "china", "impact": "中国开始八年全民族抗战"},
    {"year": 1937, "event": "南京大屠杀", "scope": "china", "impact": "日本军国主义最残暴的罪行，三十万同胞遇难"},
    {"year": 1939, "event": "第二次世界大战全面爆发", "scope": "world", "impact": "人类历史上最大规模的战争开始"},
    {"year": 1941, "event": "珍珠港事件，美国参战", "scope": "world", "impact": "二战格局根本转变，反法西斯同盟形成"},
    {"year": 1945, "event": "第二次世界大战结束", "scope": "world", "impact": "人类最惨烈的战争终结，联合国成立，冷战格局孕育"},
    {"year": 1945, "event": "美国投原子弹于广岛长崎", "scope": "world", "impact": "核武器时代来临，人类首次拥有自我毁灭的力量"},
    {"year": 1945, "event": "抗战胜利，台湾光复", "scope": "china", "impact": "中国近代首次取得反侵略战争全面胜利"},
    {"year": 1946, "event": "国共内战全面爆发", "scope": "china", "impact": "中国命运之战，决定国家未来走向"},
    {"year": 1947, "event": "印度独立与印巴分治", "scope": "world", "impact": "大英帝国殖民体系瓦解的标志性事件"},
    {"year": 1948, "event": "以色列建国，第一次中东战争", "scope": "world", "impact": "中东冲突的起点，延续至今"},
    {"year": 1949, "event": "中华人民共和国成立", "scope": "china", "impact": "中国历史根本转折，社会主义中国崛起"},
    {"year": 1949, "event": "北约成立", "scope": "world", "impact": "西方军事同盟体系建立，冷战格局制度化"},
    {"year": 1950, "event": "朝鲜战争爆发，中国抗美援朝", "scope": "china", "impact": "新中国立国之战，确立大国地位"},
    {"year": 1953, "event": "DNA双螺旋结构发现", "scope": "world", "impact": "分子生物学革命，开启基因时代"},
    {"year": 1955, "event": "万隆会议，不结盟运动兴起", "scope": "world", "impact": "第三世界国家开始独立发声"},
    {"year": 1957, "event": "苏联发射第一颗人造卫星", "scope": "world", "impact": "太空时代来临，美苏太空竞赛开始"},
    {"year": 1958, "event": "大跃进运动开始", "scope": "china", "impact": "经济冒进导致大饥荒，造成严重灾难"},
    {"year": 1962, "event": "古巴导弹危机", "scope": "world", "impact": "人类最接近核战争的时刻"},
    {"year": 1964, "event": "中国第一颗原子弹爆炸成功", "scope": "china", "impact": "中国跻身核大国，国家安全根本保障"},
    {"year": 1966, "event": "文化大革命开始", "scope": "china", "impact": "十年浩劫，经济文化社会遭受严重破坏"},
    {"year": 1969, "event": "人类首次登月", "scope": "world", "impact": "人类太空探索的巅峰时刻"},
    {"year": 1971, "event": "中国恢复联合国合法席位", "scope": "china", "impact": "中国重返国际舞台，国际地位提升"},
    {"year": 1972, "event": "尼克松访华，中美关系破冰", "scope": "world", "impact": "冷战格局重大转变，中美苏大三角形成"},
    {"year": 1976, "event": "毛泽东逝世，文化大革命结束", "scope": "china", "impact": "中国历史转折点，新时代即将来临"},
    {"year": 1978, "event": "改革开放开始", "scope": "china", "impact": "中国经济发展最关键的转折，四十年高速增长的开端"},
    {"year": 1979, "event": "中越战争", "scope": "china", "impact": "冷战格局下的区域冲突，影响中越关系至今"},
    {"year": 1989, "event": "柏林墙倒塌", "scope": "world", "impact": "冷战结束的标志性事件，东欧剧变"},
    {"year": 1991, "event": "苏联解体", "scope": "world", "impact": "冷战正式终结，美国成为唯一超级大国"},
    {"year": 1991, "event": "海湾战争", "scope": "world", "impact": "信息化战争时代来临，美国军力碾压性展示"},
    {"year": 1992, "event": "邓小平南巡讲话", "scope": "china", "impact": "坚定改革开放方向，市场经济体制确立"},
    {"year": 1997, "event": "香港回归中国", "scope": "china", "impact": "洗雪百年国耻，一国两制实践开始"},
    {"year": 1997, "event": "亚洲金融危机", "scope": "world", "impact": "暴露东亚经济模式弱点，区域合作加速"},
    {"year": 1999, "event": "澳门回归中国", "scope": "china", "impact": "外国在华最后一块殖民地的终结"},
    {"year": 2001, "event": "中国加入WTO", "scope": "china", "impact": "中国深度融入全球经济体系，贸易腾飞"},
    {"year": 2001, "event": "九一一恐怖袭击", "scope": "world", "impact": "全球反恐战争开始，美国战略重心转移"},
    {"year": 2003, "event": "中国首次载人航天飞行", "scope": "china", "impact": "中国成为第三个独立将人送入太空的国家"},
    {"year": 2008, "event": "北京奥运会", "scope": "china", "impact": "中国向世界展示综合国力，国际形象提升"},
    {"year": 2008, "event": "全球金融危机", "scope": "world", "impact": "自大萧条以来最严重的经济危机，世界经济格局调整"},
    {"year": 2010, "event": "中国GDP超越日本成为世界第二", "scope": "china", "impact": "中国经济总量跃居全球第二，世界格局深刻改变"},
    {"year": 2011, "event": "阿拉伯之春", "scope": "world", "impact": "中东多国政权更迭，地区持续动荡"},
    {"year": 2013, "event": "一带一路倡议提出", "scope": "china", "impact": "中国提出全球性发展战略，重塑国际贸易格局"},
    {"year": 2015, "event": "中国发起亚投行", "scope": "china", "impact": "中国主导的国际金融机构，体现全球经济治理新格局"},
    {"year": 2016, "event": "英国脱欧公投", "scope": "world", "impact": "欧洲一体化进程受挫，民粹主义崛起"},
    {"year": 2016, "event": "AlphaGo击败世界围棋冠军", "scope": "world", "impact": "人工智能里程碑，引发全球AI浪潮"},
    {"year": 2018, "event": "中美贸易战爆发", "scope": "world", "impact": "世界两大经济体对抗，全球化进程面临逆转"},
    {"year": 2020, "event": "新冠疫情全球大流行", "scope": "world", "impact": "百年一遇的全球公共卫生危机，深刻改变社会运行方式"},
    {"year": 2021, "event": "中国宣布全面脱贫", "scope": "china", "impact": "消除绝对贫困，实现第一个百年目标"},
    {"year": 2022, "event": "俄乌战争爆发", "scope": "world", "impact": "二战后欧洲最大规模战争，全球地缘政治剧变"},
    {"year": 2022, "event": "ChatGPT发布，大模型时代来临", "scope": "world", "impact": "通用人工智能突破，第四次工业革命加速"},
    {"year": 2023, "event": "全球AI军备竞赛全面展开", "scope": "world", "impact": "各国大力投入AI研发，科技竞争白热化"},
    {"year": 2024, "event": "中国嫦娥六号月球背面采样返回", "scope": "china", "impact": "人类首次月背采样，中国深空探测领先"},
    {"year": 2025, "event": "全球AI智能体(Agent)大规模落地", "scope": "world", "impact": "AI从工具走向自主代理，重塑各行各业"},
    {"year": 2026, "event": "量子计算进入实用化初期", "scope": "world", "impact": "计算能力飞跃，密码学与材料科学面临变革"},
]


def get_events_for_year(year: int) -> list[dict]:
    """Return all historical events for a given year."""
    return [e for e in HISTORICAL_EVENTS if e["year"] == year]


def get_events_in_range(start: int, end: int) -> list[dict]:
    """Return all historical events within a year range (inclusive)."""
    return [e for e in HISTORICAL_EVENTS if start <= e["year"] <= end]


def get_events_by_scope(scope: str) -> list[dict]:
    """Return all events matching the given scope ('china' or 'world')."""
    return [e for e in HISTORICAL_EVENTS if e["scope"] == scope]
